// Generated by rstantools.  Do not edit by hand.

/*
    onlineMessageboardActivity is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    onlineMessageboardActivity is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with onlineMessageboardActivity.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_tidedsh_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_tidedsh");
    reader.add_event(211, 209, "end", "model_tidedsh");
    return reader;
}
#include <stan_meta_header.hpp>
class model_tidedsh
  : public stan::model::model_base_crtp<model_tidedsh> {
private:
        int N;
        int N_immigrant;
        int N_offspring;
        double a;
        double b;
        vector_d t;
        std::vector<int> v;
        int is_ds;
        int K;
        std::vector<double> f;
        int ind_immigrant;
        vector_d t_immigrant;
        int ind_offspring;
        vector_d t_offspring;
        std::vector<int> v_offspring;
        vector_d z;
        int N_latent;
        vector_d w;
        matrix_d sinusoidal_basis;
        matrix_d sinusoidal_basis_immigrant;
        matrix_d sinusoidal_basis_offspring;
        vector_d sinusoidal_basis_integral;
public:
    model_tidedsh(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_tidedsh(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_tidedsh_namespace::model_tidedsh";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 0);
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "N_immigrant", "int", context__.to_vec());
            N_immigrant = int(0);
            vals_i__ = context__.vals_i("N_immigrant");
            pos__ = 0;
            N_immigrant = vals_i__[pos__++];
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "N_offspring", "int", context__.to_vec());
            N_offspring = int(0);
            vals_i__ = context__.vals_i("N_offspring");
            pos__ = 0;
            N_offspring = vals_i__[pos__++];
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "a", "double", context__.to_vec());
            a = double(0);
            vals_r__ = context__.vals_r("a");
            pos__ = 0;
            a = vals_r__[pos__++];
            current_statement_begin__ = 11;
            context__.validate_dims("data initialization", "b", "double", context__.to_vec());
            b = double(0);
            vals_r__ = context__.vals_r("b");
            pos__ = 0;
            b = vals_r__[pos__++];
            check_greater_or_equal(function__, "b", b, a);
            current_statement_begin__ = 12;
            validate_non_negative_index("t", "N", N);
            context__.validate_dims("data initialization", "t", "vector_d", context__.to_vec(N));
            t = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("t");
            pos__ = 0;
            size_t t_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < t_j_1_max__; ++j_1__) {
                t(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "t", t, a);
            check_less_or_equal(function__, "t", t, b);
            current_statement_begin__ = 13;
            validate_non_negative_index("v", "N", N);
            context__.validate_dims("data initialization", "v", "int", context__.to_vec(N));
            v = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("v");
            pos__ = 0;
            size_t v_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < v_k_0_max__; ++k_0__) {
                v[k_0__] = vals_i__[pos__++];
            }
            size_t v_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < v_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "v[i_0__]", v[i_0__], 0);
                check_less_or_equal(function__, "v[i_0__]", v[i_0__], N);
            }
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "is_ds", "int", context__.to_vec());
            is_ds = int(0);
            vals_i__ = context__.vals_i("is_ds");
            pos__ = 0;
            is_ds = vals_i__[pos__++];
            check_greater_or_equal(function__, "is_ds", is_ds, 0);
            check_less_or_equal(function__, "is_ds", is_ds, 1);
            current_statement_begin__ = 16;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            current_statement_begin__ = 17;
            validate_non_negative_index("f", "K", K);
            context__.validate_dims("data initialization", "f", "double", context__.to_vec(K));
            f = std::vector<double>(K, double(0));
            vals_r__ = context__.vals_r("f");
            pos__ = 0;
            size_t f_k_0_max__ = K;
            for (size_t k_0__ = 0; k_0__ < f_k_0_max__; ++k_0__) {
                f[k_0__] = vals_r__[pos__++];
            }
            size_t f_i_0_max__ = K;
            for (size_t i_0__ = 0; i_0__ < f_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "f[i_0__]", f[i_0__], 0);
            }
            // initialize transformed data variables
            current_statement_begin__ = 20;
            ind_immigrant = int(0);
            stan::math::fill(ind_immigrant, std::numeric_limits<int>::min());
            current_statement_begin__ = 21;
            validate_non_negative_index("t_immigrant", "N_immigrant", N_immigrant);
            t_immigrant = Eigen::Matrix<double, Eigen::Dynamic, 1>(N_immigrant);
            stan::math::fill(t_immigrant, DUMMY_VAR__);
            current_statement_begin__ = 22;
            ind_offspring = int(0);
            stan::math::fill(ind_offspring, std::numeric_limits<int>::min());
            current_statement_begin__ = 23;
            validate_non_negative_index("t_offspring", "N_offspring", N_offspring);
            t_offspring = Eigen::Matrix<double, Eigen::Dynamic, 1>(N_offspring);
            stan::math::fill(t_offspring, DUMMY_VAR__);
            current_statement_begin__ = 24;
            validate_non_negative_index("v_offspring", "N_offspring", N_offspring);
            v_offspring = std::vector<int>(N_offspring, int(0));
            stan::math::fill(v_offspring, std::numeric_limits<int>::min());
            current_statement_begin__ = 25;
            validate_non_negative_index("z", "N", N);
            z = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            stan::math::fill(z, DUMMY_VAR__);
            current_statement_begin__ = 26;
            N_latent = int(0);
            stan::math::fill(N_latent, std::numeric_limits<int>::min());
            current_statement_begin__ = 27;
            validate_non_negative_index("w", "K", K);
            w = Eigen::Matrix<double, Eigen::Dynamic, 1>(K);
            stan::math::fill(w, DUMMY_VAR__);
            current_statement_begin__ = 28;
            validate_non_negative_index("sinusoidal_basis", "N", N);
            validate_non_negative_index("sinusoidal_basis", "(2 * K)", (2 * K));
            sinusoidal_basis = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, (2 * K));
            stan::math::fill(sinusoidal_basis, DUMMY_VAR__);
            current_statement_begin__ = 29;
            validate_non_negative_index("sinusoidal_basis_immigrant", "N_immigrant", N_immigrant);
            validate_non_negative_index("sinusoidal_basis_immigrant", "(2 * K)", (2 * K));
            sinusoidal_basis_immigrant = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N_immigrant, (2 * K));
            stan::math::fill(sinusoidal_basis_immigrant, DUMMY_VAR__);
            current_statement_begin__ = 30;
            validate_non_negative_index("sinusoidal_basis_offspring", "N_offspring", N_offspring);
            validate_non_negative_index("sinusoidal_basis_offspring", "(2 * K)", (2 * K));
            sinusoidal_basis_offspring = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N_offspring, (2 * K));
            stan::math::fill(sinusoidal_basis_offspring, DUMMY_VAR__);
            current_statement_begin__ = 31;
            validate_non_negative_index("sinusoidal_basis_integral", "(2 * K)", (2 * K));
            sinusoidal_basis_integral = Eigen::Matrix<double, Eigen::Dynamic, 1>((2 * K));
            stan::math::fill(sinusoidal_basis_integral, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 34;
            stan::math::assign(ind_immigrant, 0);
            current_statement_begin__ = 35;
            stan::math::assign(ind_offspring, 0);
            current_statement_begin__ = 36;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 37;
                if (as_bool(logical_eq(get_base1(v, i, "v", 1), 0))) {
                    current_statement_begin__ = 38;
                    stan::math::assign(ind_immigrant, (ind_immigrant + 1));
                    current_statement_begin__ = 39;
                    stan::model::assign(t_immigrant, 
                                stan::model::cons_list(stan::model::index_uni(ind_immigrant), stan::model::nil_index_list()), 
                                get_base1(t, i, "t", 1), 
                                "assigning variable t_immigrant");
                } else {
                    current_statement_begin__ = 41;
                    stan::math::assign(ind_offspring, (ind_offspring + 1));
                    current_statement_begin__ = 42;
                    stan::model::assign(t_offspring, 
                                stan::model::cons_list(stan::model::index_uni(ind_offspring), stan::model::nil_index_list()), 
                                get_base1(t, i, "t", 1), 
                                "assigning variable t_offspring");
                    current_statement_begin__ = 43;
                    stan::model::assign(v_offspring, 
                                stan::model::cons_list(stan::model::index_uni(ind_offspring), stan::model::nil_index_list()), 
                                get_base1(v, i, "v", 1), 
                                "assigning variable v_offspring");
                }
            }
            current_statement_begin__ = 46;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 47;
                stan::model::assign(z, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable z");
                current_statement_begin__ = 48;
                for (int j = (i + 1); j <= N; ++j) {
                    current_statement_begin__ = 49;
                    stan::model::assign(z, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (get_base1(z, i, "z", 1) + logical_eq(get_base1(v, j, "v", 1), i)), 
                                "assigning variable z");
                }
            }
            current_statement_begin__ = 52;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 53;
                stan::math::assign(N_latent, N);
            } else {
                current_statement_begin__ = 55;
                stan::math::assign(N_latent, 0);
            }
            current_statement_begin__ = 58;
            for (int k = 1; k <= K; ++k) {
                current_statement_begin__ = 59;
                stan::model::assign(w, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            ((2 * stan::math::pi()) * get_base1(f, k, "f", 1)), 
                            "assigning variable w");
                current_statement_begin__ = 60;
                stan::model::assign(sinusoidal_basis, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(((2 * k) - 1)), stan::model::nil_index_list())), 
                            stan::math::sin(multiply(get_base1(w, k, "w", 1), t)), 
                            "assigning variable sinusoidal_basis");
                current_statement_begin__ = 61;
                stan::model::assign(sinusoidal_basis, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((2 * k)), stan::model::nil_index_list())), 
                            stan::math::cos(multiply(get_base1(w, k, "w", 1), t)), 
                            "assigning variable sinusoidal_basis");
                current_statement_begin__ = 62;
                stan::model::assign(sinusoidal_basis_immigrant, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(((2 * k) - 1)), stan::model::nil_index_list())), 
                            stan::math::sin(multiply(get_base1(w, k, "w", 1), t_immigrant)), 
                            "assigning variable sinusoidal_basis_immigrant");
                current_statement_begin__ = 63;
                stan::model::assign(sinusoidal_basis_immigrant, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((2 * k)), stan::model::nil_index_list())), 
                            stan::math::cos(multiply(get_base1(w, k, "w", 1), t_immigrant)), 
                            "assigning variable sinusoidal_basis_immigrant");
                current_statement_begin__ = 64;
                stan::model::assign(sinusoidal_basis_offspring, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(((2 * k) - 1)), stan::model::nil_index_list())), 
                            stan::math::sin(multiply(get_base1(w, k, "w", 1), t_offspring)), 
                            "assigning variable sinusoidal_basis_offspring");
                current_statement_begin__ = 65;
                stan::model::assign(sinusoidal_basis_offspring, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((2 * k)), stan::model::nil_index_list())), 
                            stan::math::cos(multiply(get_base1(w, k, "w", 1), t_offspring)), 
                            "assigning variable sinusoidal_basis_offspring");
                current_statement_begin__ = 66;
                stan::model::assign(sinusoidal_basis_integral, 
                            stan::model::cons_list(stan::model::index_uni(((2 * k) - 1)), stan::model::nil_index_list()), 
                            ((stan::math::cos((a * get_base1(w, k, "w", 1))) - stan::math::cos((b * get_base1(w, k, "w", 1)))) / get_base1(w, k, "w", 1)), 
                            "assigning variable sinusoidal_basis_integral");
                current_statement_begin__ = 67;
                stan::model::assign(sinusoidal_basis_integral, 
                            stan::model::cons_list(stan::model::index_uni((2 * k)), stan::model::nil_index_list()), 
                            ((stan::math::sin((b * get_base1(w, k, "w", 1))) - stan::math::sin((a * get_base1(w, k, "w", 1)))) / get_base1(w, k, "w", 1)), 
                            "assigning variable sinusoidal_basis_integral");
            }
            // validate transformed data
            current_statement_begin__ = 25;
            check_greater_or_equal(function__, "z", z, 0);
            check_less_or_equal(function__, "z", z, N);
            current_statement_begin__ = 27;
            check_greater_or_equal(function__, "w", w, 0);
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 72;
            num_params_r__ += 1;
            current_statement_begin__ = 73;
            validate_non_negative_index("log_alpha", "is_ds", is_ds);
            num_params_r__ += (1 * is_ds);
            current_statement_begin__ = 75;
            num_params_r__ += 1;
            current_statement_begin__ = 78;
            validate_non_negative_index("nu", "N_latent", N_latent);
            num_params_r__ += N_latent;
            current_statement_begin__ = 79;
            num_params_r__ += 1;
            current_statement_begin__ = 80;
            validate_non_negative_index("beta", "(2 * K)", (2 * K));
            num_params_r__ += (2 * K);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_tidedsh() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 72;
        if (!(context__.contains_r("mu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu", "double", context__.to_vec());
        double mu(0);
        mu = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, mu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 73;
        if (!(context__.contains_r("log_alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable log_alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("log_alpha");
        pos__ = 0U;
        validate_non_negative_index("log_alpha", "is_ds", is_ds);
        context__.validate_dims("parameter initialization", "log_alpha", "double", context__.to_vec(is_ds));
        std::vector<double> log_alpha(is_ds, double(0));
        size_t log_alpha_k_0_max__ = is_ds;
        for (size_t k_0__ = 0; k_0__ < log_alpha_k_0_max__; ++k_0__) {
            log_alpha[k_0__] = vals_r__[pos__++];
        }
        size_t log_alpha_i_0_max__ = is_ds;
        for (size_t i_0__ = 0; i_0__ < log_alpha_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_unconstrain(log_alpha[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable log_alpha: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 75;
        if (!(context__.contains_r("R")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable R missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("R");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "R", "double", context__.to_vec());
        double R(0);
        R = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, R);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable R: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 78;
        if (!(context__.contains_r("nu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable nu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("nu");
        pos__ = 0U;
        validate_non_negative_index("nu", "N_latent", N_latent);
        context__.validate_dims("parameter initialization", "nu", "vector_d", context__.to_vec(N_latent));
        Eigen::Matrix<double, Eigen::Dynamic, 1> nu(N_latent);
        size_t nu_j_1_max__ = N_latent;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            nu(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, nu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable nu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 79;
        if (!(context__.contains_r("eta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable eta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("eta");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "eta", "double", context__.to_vec());
        double eta(0);
        eta = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, eta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable eta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 80;
        if (!(context__.contains_r("beta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta");
        pos__ = 0U;
        validate_non_negative_index("beta", "(2 * K)", (2 * K));
        context__.validate_dims("parameter initialization", "beta", "vector_d", context__.to_vec((2 * K)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta((2 * K));
        size_t beta_j_1_max__ = (2 * K);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            beta(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lub_unconstrain(-(1), 1, beta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 72;
            local_scalar_t__ mu;
            (void) mu;  // dummy to suppress unused var warning
            if (jacobian__)
                mu = in__.scalar_lb_constrain(0, lp__);
            else
                mu = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 73;
            std::vector<local_scalar_t__> log_alpha;
            size_t log_alpha_d_0_max__ = is_ds;
            log_alpha.reserve(log_alpha_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < log_alpha_d_0_max__; ++d_0__) {
                if (jacobian__)
                    log_alpha.push_back(in__.scalar_constrain(lp__));
                else
                    log_alpha.push_back(in__.scalar_constrain());
            }
            current_statement_begin__ = 75;
            local_scalar_t__ R;
            (void) R;  // dummy to suppress unused var warning
            if (jacobian__)
                R = in__.scalar_lb_constrain(0, lp__);
            else
                R = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 78;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> nu;
            (void) nu;  // dummy to suppress unused var warning
            if (jacobian__)
                nu = in__.vector_lb_constrain(0, N_latent, lp__);
            else
                nu = in__.vector_lb_constrain(0, N_latent);
            current_statement_begin__ = 79;
            local_scalar_t__ eta;
            (void) eta;  // dummy to suppress unused var warning
            if (jacobian__)
                eta = in__.scalar_lb_constrain(0, lp__);
            else
                eta = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 80;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta;
            (void) beta;  // dummy to suppress unused var warning
            if (jacobian__)
                beta = in__.vector_lub_constrain(-(1), 1, (2 * K), lp__);
            else
                beta = in__.vector_lub_constrain(-(1), 1, (2 * K));
            // transformed parameters
            current_statement_begin__ = 84;
            validate_non_negative_index("alpha", "is_ds", is_ds);
            std::vector<local_scalar_t__> alpha(is_ds, local_scalar_t__(0));
            stan::math::initialize(alpha, DUMMY_VAR__);
            stan::math::fill(alpha, DUMMY_VAR__);
            current_statement_begin__ = 85;
            validate_non_negative_index("rho", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> rho(N);
            stan::math::initialize(rho, DUMMY_VAR__);
            stan::math::fill(rho, DUMMY_VAR__);
            current_statement_begin__ = 86;
            validate_non_negative_index("rho_immigrant", "N_immigrant", N_immigrant);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> rho_immigrant(N_immigrant);
            stan::math::initialize(rho_immigrant, DUMMY_VAR__);
            stan::math::fill(rho_immigrant, DUMMY_VAR__);
            current_statement_begin__ = 87;
            validate_non_negative_index("rho_offspring", "N_offspring", N_offspring);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> rho_offspring(N_offspring);
            stan::math::initialize(rho_offspring, DUMMY_VAR__);
            stan::math::fill(rho_offspring, DUMMY_VAR__);
            current_statement_begin__ = 88;
            validate_non_negative_index("exp_sinusoidal_basis_integral", "N", N);
            validate_non_negative_index("exp_sinusoidal_basis_integral", "(2 * K)", (2 * K));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> exp_sinusoidal_basis_integral(N, (2 * K));
            stan::math::initialize(exp_sinusoidal_basis_integral, DUMMY_VAR__);
            stan::math::fill(exp_sinusoidal_basis_integral, DUMMY_VAR__);
            current_statement_begin__ = 89;
            local_scalar_t__ immigrant_log_intensity;
            (void) immigrant_log_intensity;  // dummy to suppress unused var warning
            stan::math::initialize(immigrant_log_intensity, DUMMY_VAR__);
            stan::math::fill(immigrant_log_intensity, DUMMY_VAR__);
            current_statement_begin__ = 90;
            local_scalar_t__ immigrant_scalar;
            (void) immigrant_scalar;  // dummy to suppress unused var warning
            stan::math::initialize(immigrant_scalar, DUMMY_VAR__);
            stan::math::fill(immigrant_scalar, DUMMY_VAR__);
            current_statement_begin__ = 91;
            validate_non_negative_index("tmp_offspring_log_intensity_vector", "N_offspring", N_offspring);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> tmp_offspring_log_intensity_vector(N_offspring);
            stan::math::initialize(tmp_offspring_log_intensity_vector, DUMMY_VAR__);
            stan::math::fill(tmp_offspring_log_intensity_vector, DUMMY_VAR__);
            current_statement_begin__ = 92;
            validate_non_negative_index("tmp_offspring_scalar_vector", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> tmp_offspring_scalar_vector(N);
            stan::math::initialize(tmp_offspring_scalar_vector, DUMMY_VAR__);
            stan::math::fill(tmp_offspring_scalar_vector, DUMMY_VAR__);
            current_statement_begin__ = 93;
            local_scalar_t__ offspring_log_intensity;
            (void) offspring_log_intensity;  // dummy to suppress unused var warning
            stan::math::initialize(offspring_log_intensity, DUMMY_VAR__);
            stan::math::fill(offspring_log_intensity, DUMMY_VAR__);
            current_statement_begin__ = 94;
            local_scalar_t__ offspring_scalar;
            (void) offspring_scalar;  // dummy to suppress unused var warning
            stan::math::initialize(offspring_scalar, DUMMY_VAR__);
            stan::math::fill(offspring_scalar, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 97;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 98;
                stan::math::assign(alpha, stan::math::exp(log_alpha));
            }
            current_statement_begin__ = 100;
            stan::math::assign(rho, rep_vector(1, N));
            current_statement_begin__ = 101;
            stan::math::assign(rho_immigrant, rep_vector(1, N_immigrant));
            current_statement_begin__ = 102;
            stan::math::assign(rho_offspring, rep_vector(1, N_offspring));
            current_statement_begin__ = 103;
            if (as_bool(logical_neq(K, 0))) {
                current_statement_begin__ = 104;
                stan::math::assign(rho, add(rho, multiply(sinusoidal_basis, beta)));
                current_statement_begin__ = 105;
                stan::math::assign(rho_immigrant, add(rho_immigrant, multiply(sinusoidal_basis_immigrant, beta)));
                current_statement_begin__ = 106;
                stan::math::assign(rho_offspring, add(rho_offspring, multiply(sinusoidal_basis_offspring, beta)));
            }
            current_statement_begin__ = 108;
            for (int k = 1; k <= K; ++k) {
                current_statement_begin__ = 109;
                stan::model::assign(exp_sinusoidal_basis_integral, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(((2 * k) - 1)), stan::model::nil_index_list())), 
                            multiply((eta / (pow(eta, 2) + pow(get_base1(w, k, "w", 1), 2))), add(multiply(eta, subtract(stan::math::sin(multiply(get_base1(w, k, "w", 1), t)), multiply(stan::math::sin((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))))), multiply(get_base1(w, k, "w", 1), subtract(stan::math::cos(multiply(get_base1(w, k, "w", 1), t)), multiply(stan::math::cos((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))))))), 
                            "assigning variable exp_sinusoidal_basis_integral");
                current_statement_begin__ = 113;
                stan::model::assign(exp_sinusoidal_basis_integral, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((2 * k)), stan::model::nil_index_list())), 
                            multiply((eta / (pow(eta, 2) + pow(get_base1(w, k, "w", 1), 2))), subtract(multiply(get_base1(w, k, "w", 1), subtract(multiply(stan::math::sin((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))), stan::math::sin(multiply(get_base1(w, k, "w", 1), t)))), multiply(eta, subtract(multiply(stan::math::cos((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))), stan::math::cos(multiply(get_base1(w, k, "w", 1), t)))))), 
                            "assigning variable exp_sinusoidal_basis_integral");
            }
            current_statement_begin__ = 120;
            stan::math::assign(immigrant_log_intensity, ((N_immigrant * stan::math::log(mu)) + sum(stan::math::log(rho_immigrant))));
            current_statement_begin__ = 122;
            stan::math::assign(immigrant_scalar, (b - a));
            current_statement_begin__ = 123;
            if (as_bool(logical_neq(K, 0))) {
                current_statement_begin__ = 124;
                stan::math::assign(immigrant_scalar, (immigrant_scalar + multiply(transpose(sinusoidal_basis_integral), beta)));
            }
            current_statement_begin__ = 126;
            stan::math::assign(immigrant_scalar, (mu * immigrant_scalar));
            current_statement_begin__ = 130;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 131;
                stan::math::assign(offspring_log_intensity, sum(elt_multiply(z, stan::math::log(nu))));
            } else {
                current_statement_begin__ = 133;
                stan::math::assign(offspring_log_intensity, (N_offspring * stan::math::log(R)));
            }
            current_statement_begin__ = 136;
            stan::math::assign(offspring_log_intensity, (offspring_log_intensity + sum(stan::math::log(rho_offspring))));
            current_statement_begin__ = 138;
            for (int i = 1; i <= N_offspring; ++i) {
                current_statement_begin__ = 139;
                stan::model::assign(tmp_offspring_log_intensity_vector, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            exponential_log((get_base1(t_offspring, i, "t_offspring", 1) - get_base1(t, get_base1(v_offspring, i, "v_offspring", 1), "t", 1)), eta), 
                            "assigning variable tmp_offspring_log_intensity_vector");
            }
            current_statement_begin__ = 141;
            stan::math::assign(offspring_log_intensity, (offspring_log_intensity + sum(tmp_offspring_log_intensity_vector)));
            current_statement_begin__ = 143;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 144;
                stan::model::assign(tmp_offspring_scalar_vector, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            exponential_cdf((b - get_base1(t, i, "t", 1)), eta), 
                            "assigning variable tmp_offspring_scalar_vector");
            }
            current_statement_begin__ = 146;
            if (as_bool(logical_neq(K, 0))) {
                current_statement_begin__ = 147;
                stan::math::assign(tmp_offspring_scalar_vector, add(tmp_offspring_scalar_vector, multiply(exp_sinusoidal_basis_integral, beta)));
            }
            current_statement_begin__ = 149;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 150;
                stan::math::assign(offspring_scalar, sum(elt_multiply(nu, tmp_offspring_scalar_vector)));
            } else {
                current_statement_begin__ = 152;
                stan::math::assign(offspring_scalar, (R * sum(tmp_offspring_scalar_vector)));
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 84;
            size_t alpha_k_0_max__ = is_ds;
            for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(alpha[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: alpha" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable alpha: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            size_t alpha_i_0_max__ = is_ds;
            for (size_t i_0__ = 0; i_0__ < alpha_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "alpha[i_0__]", alpha[i_0__], 0);
            }
            current_statement_begin__ = 85;
            size_t rho_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(rho(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: rho" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable rho: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "rho", rho, 0);
            current_statement_begin__ = 86;
            size_t rho_immigrant_j_1_max__ = N_immigrant;
            for (size_t j_1__ = 0; j_1__ < rho_immigrant_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(rho_immigrant(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: rho_immigrant" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable rho_immigrant: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "rho_immigrant", rho_immigrant, 0);
            current_statement_begin__ = 87;
            size_t rho_offspring_j_1_max__ = N_offspring;
            for (size_t j_1__ = 0; j_1__ < rho_offspring_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(rho_offspring(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: rho_offspring" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable rho_offspring: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "rho_offspring", rho_offspring, 0);
            current_statement_begin__ = 88;
            size_t exp_sinusoidal_basis_integral_j_1_max__ = N;
            size_t exp_sinusoidal_basis_integral_j_2_max__ = (2 * K);
            for (size_t j_1__ = 0; j_1__ < exp_sinusoidal_basis_integral_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < exp_sinusoidal_basis_integral_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(exp_sinusoidal_basis_integral(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: exp_sinusoidal_basis_integral" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable exp_sinusoidal_basis_integral: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 89;
            if (stan::math::is_uninitialized(immigrant_log_intensity)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: immigrant_log_intensity";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable immigrant_log_intensity: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 90;
            if (stan::math::is_uninitialized(immigrant_scalar)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: immigrant_scalar";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable immigrant_scalar: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            check_greater_or_equal(function__, "immigrant_scalar", immigrant_scalar, 0);
            current_statement_begin__ = 91;
            size_t tmp_offspring_log_intensity_vector_j_1_max__ = N_offspring;
            for (size_t j_1__ = 0; j_1__ < tmp_offspring_log_intensity_vector_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(tmp_offspring_log_intensity_vector(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: tmp_offspring_log_intensity_vector" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable tmp_offspring_log_intensity_vector: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 92;
            size_t tmp_offspring_scalar_vector_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < tmp_offspring_scalar_vector_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(tmp_offspring_scalar_vector(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: tmp_offspring_scalar_vector" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable tmp_offspring_scalar_vector: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "tmp_offspring_scalar_vector", tmp_offspring_scalar_vector, 0);
            current_statement_begin__ = 93;
            if (stan::math::is_uninitialized(offspring_log_intensity)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: offspring_log_intensity";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable offspring_log_intensity: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 94;
            if (stan::math::is_uninitialized(offspring_scalar)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: offspring_scalar";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable offspring_scalar: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            check_greater_or_equal(function__, "offspring_scalar", offspring_scalar, 0);
            // model body
            current_statement_begin__ = 163;
            lp_accum__.add(immigrant_log_intensity);
            current_statement_begin__ = 164;
            lp_accum__.add(-(immigrant_scalar));
            current_statement_begin__ = 165;
            lp_accum__.add(offspring_log_intensity);
            current_statement_begin__ = 166;
            lp_accum__.add(-(offspring_scalar));
            current_statement_begin__ = 171;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 172;
                lp_accum__.add(gamma_log(nu, get_base1(alpha, is_ds, "alpha", 1), (get_base1(alpha, is_ds, "alpha", 1) / R)));
                current_statement_begin__ = 173;
                lp_accum__.add(normal_log(log_alpha, 0, 1));
            }
            current_statement_begin__ = 182;
            lp_accum__.add(uniform_log(beta, -(1), 1));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("mu");
        names__.push_back("log_alpha");
        names__.push_back("R");
        names__.push_back("nu");
        names__.push_back("eta");
        names__.push_back("beta");
        names__.push_back("alpha");
        names__.push_back("rho");
        names__.push_back("rho_immigrant");
        names__.push_back("rho_offspring");
        names__.push_back("exp_sinusoidal_basis_integral");
        names__.push_back("immigrant_log_intensity");
        names__.push_back("immigrant_scalar");
        names__.push_back("tmp_offspring_log_intensity_vector");
        names__.push_back("tmp_offspring_scalar_vector");
        names__.push_back("offspring_log_intensity");
        names__.push_back("offspring_scalar");
        names__.push_back("A");
        names__.push_back("phase");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(is_ds);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_latent);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((2 * K));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(is_ds);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_immigrant);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_offspring);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back((2 * K));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_offspring);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_tidedsh_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double mu = in__.scalar_lb_constrain(0);
        vars__.push_back(mu);
        std::vector<double> log_alpha;
        size_t log_alpha_d_0_max__ = is_ds;
        log_alpha.reserve(log_alpha_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < log_alpha_d_0_max__; ++d_0__) {
            log_alpha.push_back(in__.scalar_constrain());
        }
        size_t log_alpha_k_0_max__ = is_ds;
        for (size_t k_0__ = 0; k_0__ < log_alpha_k_0_max__; ++k_0__) {
            vars__.push_back(log_alpha[k_0__]);
        }
        double R = in__.scalar_lb_constrain(0);
        vars__.push_back(R);
        Eigen::Matrix<double, Eigen::Dynamic, 1> nu = in__.vector_lb_constrain(0, N_latent);
        size_t nu_j_1_max__ = N_latent;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            vars__.push_back(nu(j_1__));
        }
        double eta = in__.scalar_lb_constrain(0);
        vars__.push_back(eta);
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta = in__.vector_lub_constrain(-(1), 1, (2 * K));
        size_t beta_j_1_max__ = (2 * K);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            vars__.push_back(beta(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 84;
            validate_non_negative_index("alpha", "is_ds", is_ds);
            std::vector<double> alpha(is_ds, double(0));
            stan::math::initialize(alpha, DUMMY_VAR__);
            stan::math::fill(alpha, DUMMY_VAR__);
            current_statement_begin__ = 85;
            validate_non_negative_index("rho", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> rho(N);
            stan::math::initialize(rho, DUMMY_VAR__);
            stan::math::fill(rho, DUMMY_VAR__);
            current_statement_begin__ = 86;
            validate_non_negative_index("rho_immigrant", "N_immigrant", N_immigrant);
            Eigen::Matrix<double, Eigen::Dynamic, 1> rho_immigrant(N_immigrant);
            stan::math::initialize(rho_immigrant, DUMMY_VAR__);
            stan::math::fill(rho_immigrant, DUMMY_VAR__);
            current_statement_begin__ = 87;
            validate_non_negative_index("rho_offspring", "N_offspring", N_offspring);
            Eigen::Matrix<double, Eigen::Dynamic, 1> rho_offspring(N_offspring);
            stan::math::initialize(rho_offspring, DUMMY_VAR__);
            stan::math::fill(rho_offspring, DUMMY_VAR__);
            current_statement_begin__ = 88;
            validate_non_negative_index("exp_sinusoidal_basis_integral", "N", N);
            validate_non_negative_index("exp_sinusoidal_basis_integral", "(2 * K)", (2 * K));
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> exp_sinusoidal_basis_integral(N, (2 * K));
            stan::math::initialize(exp_sinusoidal_basis_integral, DUMMY_VAR__);
            stan::math::fill(exp_sinusoidal_basis_integral, DUMMY_VAR__);
            current_statement_begin__ = 89;
            double immigrant_log_intensity;
            (void) immigrant_log_intensity;  // dummy to suppress unused var warning
            stan::math::initialize(immigrant_log_intensity, DUMMY_VAR__);
            stan::math::fill(immigrant_log_intensity, DUMMY_VAR__);
            current_statement_begin__ = 90;
            double immigrant_scalar;
            (void) immigrant_scalar;  // dummy to suppress unused var warning
            stan::math::initialize(immigrant_scalar, DUMMY_VAR__);
            stan::math::fill(immigrant_scalar, DUMMY_VAR__);
            current_statement_begin__ = 91;
            validate_non_negative_index("tmp_offspring_log_intensity_vector", "N_offspring", N_offspring);
            Eigen::Matrix<double, Eigen::Dynamic, 1> tmp_offspring_log_intensity_vector(N_offspring);
            stan::math::initialize(tmp_offspring_log_intensity_vector, DUMMY_VAR__);
            stan::math::fill(tmp_offspring_log_intensity_vector, DUMMY_VAR__);
            current_statement_begin__ = 92;
            validate_non_negative_index("tmp_offspring_scalar_vector", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> tmp_offspring_scalar_vector(N);
            stan::math::initialize(tmp_offspring_scalar_vector, DUMMY_VAR__);
            stan::math::fill(tmp_offspring_scalar_vector, DUMMY_VAR__);
            current_statement_begin__ = 93;
            double offspring_log_intensity;
            (void) offspring_log_intensity;  // dummy to suppress unused var warning
            stan::math::initialize(offspring_log_intensity, DUMMY_VAR__);
            stan::math::fill(offspring_log_intensity, DUMMY_VAR__);
            current_statement_begin__ = 94;
            double offspring_scalar;
            (void) offspring_scalar;  // dummy to suppress unused var warning
            stan::math::initialize(offspring_scalar, DUMMY_VAR__);
            stan::math::fill(offspring_scalar, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 97;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 98;
                stan::math::assign(alpha, stan::math::exp(log_alpha));
            }
            current_statement_begin__ = 100;
            stan::math::assign(rho, rep_vector(1, N));
            current_statement_begin__ = 101;
            stan::math::assign(rho_immigrant, rep_vector(1, N_immigrant));
            current_statement_begin__ = 102;
            stan::math::assign(rho_offspring, rep_vector(1, N_offspring));
            current_statement_begin__ = 103;
            if (as_bool(logical_neq(K, 0))) {
                current_statement_begin__ = 104;
                stan::math::assign(rho, add(rho, multiply(sinusoidal_basis, beta)));
                current_statement_begin__ = 105;
                stan::math::assign(rho_immigrant, add(rho_immigrant, multiply(sinusoidal_basis_immigrant, beta)));
                current_statement_begin__ = 106;
                stan::math::assign(rho_offspring, add(rho_offspring, multiply(sinusoidal_basis_offspring, beta)));
            }
            current_statement_begin__ = 108;
            for (int k = 1; k <= K; ++k) {
                current_statement_begin__ = 109;
                stan::model::assign(exp_sinusoidal_basis_integral, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(((2 * k) - 1)), stan::model::nil_index_list())), 
                            multiply((eta / (pow(eta, 2) + pow(get_base1(w, k, "w", 1), 2))), add(multiply(eta, subtract(stan::math::sin(multiply(get_base1(w, k, "w", 1), t)), multiply(stan::math::sin((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))))), multiply(get_base1(w, k, "w", 1), subtract(stan::math::cos(multiply(get_base1(w, k, "w", 1), t)), multiply(stan::math::cos((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))))))), 
                            "assigning variable exp_sinusoidal_basis_integral");
                current_statement_begin__ = 113;
                stan::model::assign(exp_sinusoidal_basis_integral, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni((2 * k)), stan::model::nil_index_list())), 
                            multiply((eta / (pow(eta, 2) + pow(get_base1(w, k, "w", 1), 2))), subtract(multiply(get_base1(w, k, "w", 1), subtract(multiply(stan::math::sin((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))), stan::math::sin(multiply(get_base1(w, k, "w", 1), t)))), multiply(eta, subtract(multiply(stan::math::cos((get_base1(w, k, "w", 1) * b)), stan::math::exp(multiply(-(eta), subtract(b, t)))), stan::math::cos(multiply(get_base1(w, k, "w", 1), t)))))), 
                            "assigning variable exp_sinusoidal_basis_integral");
            }
            current_statement_begin__ = 120;
            stan::math::assign(immigrant_log_intensity, ((N_immigrant * stan::math::log(mu)) + sum(stan::math::log(rho_immigrant))));
            current_statement_begin__ = 122;
            stan::math::assign(immigrant_scalar, (b - a));
            current_statement_begin__ = 123;
            if (as_bool(logical_neq(K, 0))) {
                current_statement_begin__ = 124;
                stan::math::assign(immigrant_scalar, (immigrant_scalar + multiply(transpose(sinusoidal_basis_integral), beta)));
            }
            current_statement_begin__ = 126;
            stan::math::assign(immigrant_scalar, (mu * immigrant_scalar));
            current_statement_begin__ = 130;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 131;
                stan::math::assign(offspring_log_intensity, sum(elt_multiply(z, stan::math::log(nu))));
            } else {
                current_statement_begin__ = 133;
                stan::math::assign(offspring_log_intensity, (N_offspring * stan::math::log(R)));
            }
            current_statement_begin__ = 136;
            stan::math::assign(offspring_log_intensity, (offspring_log_intensity + sum(stan::math::log(rho_offspring))));
            current_statement_begin__ = 138;
            for (int i = 1; i <= N_offspring; ++i) {
                current_statement_begin__ = 139;
                stan::model::assign(tmp_offspring_log_intensity_vector, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            exponential_log((get_base1(t_offspring, i, "t_offspring", 1) - get_base1(t, get_base1(v_offspring, i, "v_offspring", 1), "t", 1)), eta), 
                            "assigning variable tmp_offspring_log_intensity_vector");
            }
            current_statement_begin__ = 141;
            stan::math::assign(offspring_log_intensity, (offspring_log_intensity + sum(tmp_offspring_log_intensity_vector)));
            current_statement_begin__ = 143;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 144;
                stan::model::assign(tmp_offspring_scalar_vector, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            exponential_cdf((b - get_base1(t, i, "t", 1)), eta), 
                            "assigning variable tmp_offspring_scalar_vector");
            }
            current_statement_begin__ = 146;
            if (as_bool(logical_neq(K, 0))) {
                current_statement_begin__ = 147;
                stan::math::assign(tmp_offspring_scalar_vector, add(tmp_offspring_scalar_vector, multiply(exp_sinusoidal_basis_integral, beta)));
            }
            current_statement_begin__ = 149;
            if (as_bool(is_ds)) {
                current_statement_begin__ = 150;
                stan::math::assign(offspring_scalar, sum(elt_multiply(nu, tmp_offspring_scalar_vector)));
            } else {
                current_statement_begin__ = 152;
                stan::math::assign(offspring_scalar, (R * sum(tmp_offspring_scalar_vector)));
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 84;
            size_t alpha_i_0_max__ = is_ds;
            for (size_t i_0__ = 0; i_0__ < alpha_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "alpha[i_0__]", alpha[i_0__], 0);
            }
            current_statement_begin__ = 85;
            check_greater_or_equal(function__, "rho", rho, 0);
            current_statement_begin__ = 86;
            check_greater_or_equal(function__, "rho_immigrant", rho_immigrant, 0);
            current_statement_begin__ = 87;
            check_greater_or_equal(function__, "rho_offspring", rho_offspring, 0);
            current_statement_begin__ = 90;
            check_greater_or_equal(function__, "immigrant_scalar", immigrant_scalar, 0);
            current_statement_begin__ = 92;
            check_greater_or_equal(function__, "tmp_offspring_scalar_vector", tmp_offspring_scalar_vector, 0);
            current_statement_begin__ = 94;
            check_greater_or_equal(function__, "offspring_scalar", offspring_scalar, 0);
            // write transformed parameters
            if (include_tparams__) {
                size_t alpha_k_0_max__ = is_ds;
                for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                    vars__.push_back(alpha[k_0__]);
                }
                size_t rho_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
                    vars__.push_back(rho(j_1__));
                }
                size_t rho_immigrant_j_1_max__ = N_immigrant;
                for (size_t j_1__ = 0; j_1__ < rho_immigrant_j_1_max__; ++j_1__) {
                    vars__.push_back(rho_immigrant(j_1__));
                }
                size_t rho_offspring_j_1_max__ = N_offspring;
                for (size_t j_1__ = 0; j_1__ < rho_offspring_j_1_max__; ++j_1__) {
                    vars__.push_back(rho_offspring(j_1__));
                }
                size_t exp_sinusoidal_basis_integral_j_2_max__ = (2 * K);
                size_t exp_sinusoidal_basis_integral_j_1_max__ = N;
                for (size_t j_2__ = 0; j_2__ < exp_sinusoidal_basis_integral_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < exp_sinusoidal_basis_integral_j_1_max__; ++j_1__) {
                        vars__.push_back(exp_sinusoidal_basis_integral(j_1__, j_2__));
                    }
                }
                vars__.push_back(immigrant_log_intensity);
                vars__.push_back(immigrant_scalar);
                size_t tmp_offspring_log_intensity_vector_j_1_max__ = N_offspring;
                for (size_t j_1__ = 0; j_1__ < tmp_offspring_log_intensity_vector_j_1_max__; ++j_1__) {
                    vars__.push_back(tmp_offspring_log_intensity_vector(j_1__));
                }
                size_t tmp_offspring_scalar_vector_j_1_max__ = N;
                for (size_t j_1__ = 0; j_1__ < tmp_offspring_scalar_vector_j_1_max__; ++j_1__) {
                    vars__.push_back(tmp_offspring_scalar_vector(j_1__));
                }
                vars__.push_back(offspring_log_intensity);
                vars__.push_back(offspring_scalar);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 198;
            validate_non_negative_index("A", "K", K);
            Eigen::Matrix<double, Eigen::Dynamic, 1> A(K);
            stan::math::initialize(A, DUMMY_VAR__);
            stan::math::fill(A, DUMMY_VAR__);
            current_statement_begin__ = 199;
            validate_non_negative_index("phase", "K", K);
            Eigen::Matrix<double, Eigen::Dynamic, 1> phase(K);
            stan::math::initialize(phase, DUMMY_VAR__);
            stan::math::fill(phase, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 205;
            for (int k = 1; k <= K; ++k) {
                current_statement_begin__ = 206;
                stan::model::assign(A, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            stan::math::sqrt((pow(get_base1(beta, ((2 * k) - 1), "beta", 1), 2) + pow(get_base1(beta, (2 * k), "beta", 1), 2))), 
                            "assigning variable A");
                current_statement_begin__ = 207;
                stan::model::assign(phase, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            atan2(get_base1(beta, (2 * k), "beta", 1), get_base1(beta, ((2 * k) - 1), "beta", 1)), 
                            "assigning variable phase");
            }
            // validate, write generated quantities
            current_statement_begin__ = 198;
            size_t A_j_1_max__ = K;
            for (size_t j_1__ = 0; j_1__ < A_j_1_max__; ++j_1__) {
                vars__.push_back(A(j_1__));
            }
            current_statement_begin__ = 199;
            size_t phase_j_1_max__ = K;
            for (size_t j_1__ = 0; j_1__ < phase_j_1_max__; ++j_1__) {
                vars__.push_back(phase(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_tidedsh";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        size_t log_alpha_k_0_max__ = is_ds;
        for (size_t k_0__ = 0; k_0__ < log_alpha_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_alpha" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "R";
        param_names__.push_back(param_name_stream__.str());
        size_t nu_j_1_max__ = N_latent;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nu" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "eta";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_j_1_max__ = (2 * K);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t alpha_k_0_max__ = is_ds;
            for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t rho_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rho" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t rho_immigrant_j_1_max__ = N_immigrant;
            for (size_t j_1__ = 0; j_1__ < rho_immigrant_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rho_immigrant" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t rho_offspring_j_1_max__ = N_offspring;
            for (size_t j_1__ = 0; j_1__ < rho_offspring_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rho_offspring" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t exp_sinusoidal_basis_integral_j_2_max__ = (2 * K);
            size_t exp_sinusoidal_basis_integral_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < exp_sinusoidal_basis_integral_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < exp_sinusoidal_basis_integral_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "exp_sinusoidal_basis_integral" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "immigrant_log_intensity";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "immigrant_scalar";
            param_names__.push_back(param_name_stream__.str());
            size_t tmp_offspring_log_intensity_vector_j_1_max__ = N_offspring;
            for (size_t j_1__ = 0; j_1__ < tmp_offspring_log_intensity_vector_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tmp_offspring_log_intensity_vector" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t tmp_offspring_scalar_vector_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < tmp_offspring_scalar_vector_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tmp_offspring_scalar_vector" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "offspring_log_intensity";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "offspring_scalar";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t A_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < A_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "A" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t phase_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < phase_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "phase" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        size_t log_alpha_k_0_max__ = is_ds;
        for (size_t k_0__ = 0; k_0__ < log_alpha_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_alpha" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "R";
        param_names__.push_back(param_name_stream__.str());
        size_t nu_j_1_max__ = N_latent;
        for (size_t j_1__ = 0; j_1__ < nu_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nu" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "eta";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_j_1_max__ = (2 * K);
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t alpha_k_0_max__ = is_ds;
            for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t rho_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < rho_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rho" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t rho_immigrant_j_1_max__ = N_immigrant;
            for (size_t j_1__ = 0; j_1__ < rho_immigrant_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rho_immigrant" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t rho_offspring_j_1_max__ = N_offspring;
            for (size_t j_1__ = 0; j_1__ < rho_offspring_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rho_offspring" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t exp_sinusoidal_basis_integral_j_2_max__ = (2 * K);
            size_t exp_sinusoidal_basis_integral_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < exp_sinusoidal_basis_integral_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < exp_sinusoidal_basis_integral_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "exp_sinusoidal_basis_integral" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "immigrant_log_intensity";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "immigrant_scalar";
            param_names__.push_back(param_name_stream__.str());
            size_t tmp_offspring_log_intensity_vector_j_1_max__ = N_offspring;
            for (size_t j_1__ = 0; j_1__ < tmp_offspring_log_intensity_vector_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tmp_offspring_log_intensity_vector" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t tmp_offspring_scalar_vector_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < tmp_offspring_scalar_vector_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "tmp_offspring_scalar_vector" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "offspring_log_intensity";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "offspring_scalar";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t A_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < A_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "A" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t phase_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < phase_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "phase" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_tidedsh_namespace::model_tidedsh stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
