#' Simulate Hawkes process cluster
#'
#' Simulate a cluster generated by the Hawkes process model up to a specified
#' horizon.. In this case, the offsprinf intensity is defined as \deqn{R \psi
#' \exp (- \psi ( t - t_i))} for \eqn{t > t_i} where \eqn{R} is the reproduction
#' number and \eqn{\psi} is the exponential decay rate for the generation
#' interval density.
#'
#' @param t_i A real valued scalar. The seeding event time.
#' @param reproduction_number A positive real valued scalar. The expected number
#'   of offspring from each event.
#' @param gi_exp_decay_rate A positive real valued scalar. The exponential rate
#'   of decay in the density function of the generation interval distribution,
#' @param horizon A real valued scalar greater than \eqn{t_i}. The time up to
#'   which events in the cluster are simulated.
#' @param cluster_id A scalar.An arbitrary cluster label.
#' @inheritParams refactor_branching_structure
#'
#' @return A data frame with 4 variables: timestamps \eqn{t}, labels
#'   \eqn{id}; parent labels \eqn{parent_id}; cluster label
#'   \eqn{cluster_id}.
#' @export
simulate_hawkes_cluster <- function(
  t_i,
  reproduction_number,
  gi_exp_decay_rate,
  horizon,
  cluster_id = 0,
  perform_checks = TRUE
  ){
  if (perform_checks) {
    checkmate::assert_number(t_i, finite = TRUE)
    checkmate::assert_number(reproduction_number, lower = 0, finite = TRUE)
    if (reproduction_number >= 1)
      warning("Careful now. reproduction_number >= 1. The cluster process is no longer stationary")
    checkmate::assert_number(gi_exp_decay_rate, lower = 0, finite = TRUE)
    checkmate::assert_number(horizon, lower = t_i, finite = TRUE)
  }
  # Initialise tree
  n <- 0
  gs <- 1
  ts <- 1
  j <- 1
  cluster_df <-data.frame(
    t = t_i,
    id = paste(cluster_id, 0, 1, sep = "."),
    parent_id = NA,
    cluster_id = cluster_id,
    gen = n,
    z = NA
  )
  # Recursivly generate offspring
  while (gs > 0) {
    n <- n + 1
    while (j <= ts) {
      tmp_F_j <-
        stats::pexp(horizon - cluster_df$t[j], rate = gi_exp_decay_rate)
      tmp_z_j <-
        stats::rpois(n = 1, lambda = reproduction_number * tmp_F_j)
      cluster_df$z[j] <- tmp_z_j
      if (tmp_z_j > 0) {
        cluster_df <- rbind(
          cluster_df,
          data.frame(
            t = cluster_df$t[j] +
              truncdist::rtrunc(
                n = tmp_z_j,
                spec = "exp",
                a = 0,
                b = horizon - cluster_df$t[j],
                rate = gi_exp_decay_rate
              ),
            id = paste(cluster_id, j, 1:tmp_z_j, sep = "."),
            parent_id = cluster_df$id[j],
            cluster_id = cluster_id,
            gen = n,
            z = NA
          )
        )
      }
      j <- j + 1
    }
    gs <- nrow(cluster_df) - ts
    ts <- nrow(cluster_df)
  }
  ord <- order(cluster_df$t)
  cluster_df <- dplyr::arrange(cluster_df, t)

  cluster_df$parent_id <- refactor_branching_structure(
    id = cluster_df$id,
    parent_id = cluster_df$parent_id,
    is_immigrant = cluster_df$gen == 0,
    S = ts,
    perform_checks = FALSE
  )
  cluster_df$id <- 1:ts
  cluster_df[, 1:4]
}
